name: Linting and style checking

on: 
  workflow_dispatch:
  pull_request:

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check lua/
          # Specify `version` to pin a specific version, otherwise action will always use latest version/automatically update
